/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-d1-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-d1-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-d1-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const projects = sqliteTable(
  "projects",
  {
    id: integer("id").primaryKey(),
    project_name: text("project_name").notNull(),
    project_description: text("project_description", {
      mode: "json",
    }).notNull(),
    project_thumbnail: integer("project_thumbnail_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    Link_label: text("link_label").notNull(),
    Link_href: text("link_href").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("projects_project_thumbnail_idx").on(columns.project_thumbnail),
    index("projects_updated_at_idx").on(columns.updatedAt),
    index("projects_created_at_idx").on(columns.createdAt),
  ],
);

export const projects_rels = sqliteTable(
  "projects_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    technologiesID: integer("technologies_id"),
  },
  (columns) => [
    index("projects_rels_order_idx").on(columns.order),
    index("projects_rels_parent_idx").on(columns.parent),
    index("projects_rels_path_idx").on(columns.path),
    index("projects_rels_technologies_id_idx").on(columns.technologiesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [projects.id],
      name: "projects_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["technologiesID"]],
      foreignColumns: [technologies.id],
      name: "projects_rels_technologies_fk",
    }).onDelete("cascade"),
  ],
);

export const resume = sqliteTable(
  "resume",
  {
    id: integer("id").primaryKey(),
    title: text("title"),
    file: integer("file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    _status: text("_status", { enum: ["draft", "published"] }).default("draft"),
  },
  (columns) => [
    index("resume_file_idx").on(columns.file),
    index("resume_updated_at_idx").on(columns.updatedAt),
    index("resume_created_at_idx").on(columns.createdAt),
    index("resume__status_idx").on(columns._status),
  ],
);

export const _resume_v = sqliteTable(
  "_resume_v",
  {
    id: integer("id").primaryKey(),
    parent: integer("parent_id").references(() => resume.id, {
      onDelete: "set null",
    }),
    version_title: text("version_title"),
    version_file: integer("version_file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_updatedAt: text("version_updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_createdAt: text("version_created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version__status: text("version__status", {
      enum: ["draft", "published"],
    }).default("draft"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    latest: integer("latest", { mode: "boolean" }),
  },
  (columns) => [
    index("_resume_v_parent_idx").on(columns.parent),
    index("_resume_v_version_version_file_idx").on(columns.version_file),
    index("_resume_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_resume_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_resume_v_version_version__status_idx").on(columns.version__status),
    index("_resume_v_created_at_idx").on(columns.createdAt),
    index("_resume_v_updated_at_idx").on(columns.updatedAt),
    index("_resume_v_latest_idx").on(columns.latest),
  ],
);

export const companies = sqliteTable(
  "companies",
  {
    id: integer("id").primaryKey(),
    company_name: text("company_name").notNull(),
    company_logo: integer("company_logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    company_website: text("company_website"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("companies_company_logo_idx").on(columns.company_logo),
    index("companies_updated_at_idx").on(columns.updatedAt),
    index("companies_created_at_idx").on(columns.createdAt),
  ],
);

export const technologies = sqliteTable(
  "technologies",
  {
    id: integer("id").primaryKey(),
    technology_name: text("technology_name").notNull(),
    technology_color: text("technology_color"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("technologies_updated_at_idx").on(columns.updatedAt),
    index("technologies_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    projectsID: integer("projects_id"),
    resumeID: integer("resume_id"),
    companiesID: integer("companies_id"),
    technologiesID: integer("technologies_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_projects_id_idx").on(
      columns.projectsID,
    ),
    index("payload_locked_documents_rels_resume_id_idx").on(columns.resumeID),
    index("payload_locked_documents_rels_companies_id_idx").on(
      columns.companiesID,
    ),
    index("payload_locked_documents_rels_technologies_id_idx").on(
      columns.technologiesID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["resumeID"]],
      foreignColumns: [resume.id],
      name: "payload_locked_documents_rels_resume_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["companiesID"]],
      foreignColumns: [companies.id],
      name: "payload_locked_documents_rels_companies_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["technologiesID"]],
      foreignColumns: [technologies.id],
      name: "payload_locked_documents_rels_technologies_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_projects_rels = relations(projects_rels, ({ one }) => ({
  parent: one(projects, {
    fields: [projects_rels.parent],
    references: [projects.id],
    relationName: "_rels",
  }),
  technologiesID: one(technologies, {
    fields: [projects_rels.technologiesID],
    references: [technologies.id],
    relationName: "technologies",
  }),
}));
export const relations_projects = relations(projects, ({ one, many }) => ({
  project_thumbnail: one(media, {
    fields: [projects.project_thumbnail],
    references: [media.id],
    relationName: "project_thumbnail",
  }),
  _rels: many(projects_rels, {
    relationName: "_rels",
  }),
}));
export const relations_resume = relations(resume, ({ one }) => ({
  file: one(media, {
    fields: [resume.file],
    references: [media.id],
    relationName: "file",
  }),
}));
export const relations__resume_v = relations(_resume_v, ({ one }) => ({
  parent: one(resume, {
    fields: [_resume_v.parent],
    references: [resume.id],
    relationName: "parent",
  }),
  version_file: one(media, {
    fields: [_resume_v.version_file],
    references: [media.id],
    relationName: "version_file",
  }),
}));
export const relations_companies = relations(companies, ({ one }) => ({
  company_logo: one(media, {
    fields: [companies.company_logo],
    references: [media.id],
    relationName: "company_logo",
  }),
}));
export const relations_technologies = relations(technologies, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
    resumeID: one(resume, {
      fields: [payload_locked_documents_rels.resumeID],
      references: [resume.id],
      relationName: "resume",
    }),
    companiesID: one(companies, {
      fields: [payload_locked_documents_rels.companiesID],
      references: [companies.id],
      relationName: "companies",
    }),
    technologiesID: one(technologies, {
      fields: [payload_locked_documents_rels.technologiesID],
      references: [technologies.id],
      relationName: "technologies",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  projects: typeof projects;
  projects_rels: typeof projects_rels;
  resume: typeof resume;
  _resume_v: typeof _resume_v;
  companies: typeof companies;
  technologies: typeof technologies;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_projects_rels: typeof relations_projects_rels;
  relations_projects: typeof relations_projects;
  relations_resume: typeof relations_resume;
  relations__resume_v: typeof relations__resume_v;
  relations_companies: typeof relations_companies;
  relations_technologies: typeof relations_technologies;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-d1-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
